from collections.abc import Sequence
from dataclasses import dataclass, field
from enum import StrEnum

import numpy

from .model import NonlinearProgram
from .options import SolverOptions
from .program import GeneratedProgram, LDLFactor, ModelValues


class Procedure(StrEnum):
    BYRD_OMOJOKUN_SOC = "byrd-omojukun-soc"
    BYRD_OMOJOKUN = "byrd-omojukun"
    PROJECTED_GRADIENT = "projected-gradient"
    CAUCHY = "cauchy"
    REJECTED = "rejected"


class ActiveSetError(RuntimeError): ...


@dataclass(slots=True)
class IterationDiagnostics:
    procedure: Procedure
    accepted: bool
    x: numpy.ndarray
    objective: float
    violation: float
    trust_radius: float
    normal_step_norm: float
    tangential_step_norm: float
    correction_step_norm: float
    active_bounds: numpy.ndarray
    equality_multipliers: numpy.ndarray
    bound_multipliers: numpy.ndarray


@dataclass(slots=True)
class SolverDiagnostics:
    iterations: list[IterationDiagnostics] = field(default_factory=list)


@dataclass(slots=True)
class SolverResult:
    x: numpy.ndarray
    diagnostics: SolverDiagnostics


@dataclass(slots=True)
class _Linearization:
    values: ModelValues
    active: numpy.ndarray
    free: numpy.ndarray
    free_jacobian: numpy.ndarray
    factor: LDLFactor


@dataclass(slots=True)
class _Step:
    compound: numpy.ndarray
    correction: numpy.ndarray
    projected_gradient: numpy.ndarray
    cauchy: numpy.ndarray
    normal_norm: float
    tangential_norm: float


class _Filter:
    def __init__(self, beta: float, gamma: float):
        self.beta = beta
        self.gamma = gamma
        self.entries: list[tuple[float, float]] = []

    def add_initial(self, objective: float, violation: float) -> None:
        self.entries.append((objective, violation))

    def accepts(self, objective: float, violation: float) -> bool:
        accepted = all(objective + self.gamma * violation <= old_objective or violation <= (1.0 - self.beta) * old_violation for old_objective, old_violation in self.entries)
        if accepted:
            self.entries.append((objective, violation))
        return accepted


class Solver:
    """Callable generated Byrd--Omojokun optimizer."""

    def __init__(self, program: GeneratedProgram, options: SolverOptions):
        self.program = program
        self.options = options

    @property
    def nlp(self) -> NonlinearProgram:
        return self.program.nlp

    @property
    def ast(self):
        """The SymPy evaluator IR used by this generated solver."""
        return self.program.ir

    def __call__(
        self,
        initial_guess: Sequence[float],
        parameters: Sequence[float] = (),
        *,
        diagnostics: bool = False,
    ) -> numpy.ndarray | SolverResult:
        result = self.solve(initial_guess, parameters)
        return result if diagnostics else result.x

    def solve(self, initial_guess: Sequence[float], parameters: Sequence[float] = ()) -> SolverResult:
        x = numpy.asarray(initial_guess, dtype=float).reshape(-1).copy()
        params = numpy.asarray(parameters, dtype=float).reshape(-1)
        if x.size != self.nlp.dimension:
            raise ValueError(f"expected {self.nlp.dimension} initial values, got {x.size}")
        if params.size != len(self.nlp.parameters):
            raise ValueError(f"expected {len(self.nlp.parameters)} parameters, got {params.size}")
        if not numpy.all(numpy.isfinite(x)) or not numpy.all(numpy.isfinite(params)):
            raise ValueError("initial values and parameters must be finite")

        initial = self.program.evaluate(x, params)
        active = numpy.zeros(self.nlp.dimension, dtype=numpy.int8)
        fixed = (
            numpy.isfinite(initial.lower_bounds) & numpy.isfinite(initial.upper_bounds) & (numpy.abs(initial.upper_bounds - initial.lower_bounds) <= self.options.bound_tolerance)
        )
        active[fixed] = -1
        counters = numpy.zeros(self.nlp.dimension, dtype=numpy.int64)
        freeze = 0
        trust_radius = self.options.initial_trust_radius
        candidate_filter = _Filter(self.options.filter_beta, self.options.filter_gamma)
        candidate_filter.add_initial(initial.objective, _violation(initial, x))
        diagnostics = SolverDiagnostics()

        for _ in range(self.options.sqp_iterations):
            current = self.program.evaluate(x, params)
            linearization = self._linearize(current, active)
            step = self._step(x, params, linearization, trust_radius)
            attempts = (
                (Procedure.BYRD_OMOJOKUN_SOC, step.compound + step.correction),
                (Procedure.BYRD_OMOJOKUN, step.compound),
                (Procedure.PROJECTED_GRADIENT, step.projected_gradient),
                (Procedure.CAUCHY, step.cauchy),
            )
            accepted = False
            chosen_procedure = Procedure.REJECTED
            chosen_step = numpy.zeros_like(x)
            chosen_values = current
            chosen_x = x
            for procedure, trial_step in attempts:
                trial_x = x + trial_step
                trial = self.program.evaluate(trial_x, params)
                trial_violation = _violation(trial, trial_x)
                if candidate_filter.accepts(trial.objective, trial_violation):
                    accepted = True
                    chosen_procedure = procedure
                    chosen_step = trial_step
                    chosen_values = trial
                    chosen_x = trial_x
                    break

            equality_multipliers = numpy.zeros(self.nlp.equality_dimension)
            bound_multipliers = numpy.zeros(self.nlp.dimension)
            if accepted:
                x = chosen_x.copy()
                actual_norm = float(numpy.linalg.norm(chosen_step))
                trust_radius = self.options.trust_expand * actual_norm
                new_linearization = self._linearize(chosen_values, active)
                equality_multipliers, bound_multipliers = self._multipliers(new_linearization)
                changed = self._maintain_active_set(
                    chosen_values,
                    x,
                    bound_multipliers,
                    active,
                    fixed,
                    counters,
                    freeze,
                )
                if changed:
                    trust_radius *= self.options.trust_shrink
                    freeze = self.options.active_set_freeze
                else:
                    freeze -= 1
            else:
                trust_radius *= self.options.trust_shrink

            trust_radius = max(trust_radius, numpy.finfo(float).eps)
            diagnostics.iterations.append(
                IterationDiagnostics(
                    chosen_procedure,
                    accepted,
                    x.copy(),
                    chosen_values.objective if accepted else current.objective,
                    _violation(chosen_values, x) if accepted else _violation(current, x),
                    trust_radius,
                    step.normal_norm,
                    step.tangential_norm,
                    float(numpy.linalg.norm(step.correction)),
                    active.copy(),
                    equality_multipliers.copy(),
                    bound_multipliers.copy(),
                )
            )

        return SolverResult(x, diagnostics)

    def _linearize(self, values: ModelValues, active: numpy.ndarray) -> _Linearization:
        number_active = int(numpy.count_nonzero(active))
        if self.nlp.equality_dimension + number_active > self.nlp.dimension:
            raise ActiveSetError("equalities plus active bounds exceed the number of variables")
        free = active == 0
        free_jacobian = values.equality_jacobian[:, free]
        gram = self.program.assemble_equality_gram(
            values.equality_jacobian,
            free,
            self.options.equality_regularization,
        )
        factor = self.program.ldl.factor(gram, self.options.factorization_tolerance)
        return _Linearization(values, active.copy(), free, free_jacobian, factor)

    def _project(self, vector: numpy.ndarray, linearization: _Linearization) -> numpy.ndarray:
        projected = numpy.zeros_like(vector)
        free_values = vector[linearization.free]
        if self.nlp.equality_dimension:
            correction = linearization.factor.solve(linearization.free_jacobian @ free_values)
            free_values = free_values - linearization.free_jacobian.T @ correction
        projected[linearization.free] = free_values
        return projected

    def _step(self, x: numpy.ndarray, parameters: numpy.ndarray, linearization: _Linearization, trust_radius: float) -> _Step:
        values = linearization.values
        normal = numpy.zeros_like(x)
        lower_active = linearization.active < 0
        upper_active = linearization.active > 0
        normal[lower_active] = values.lower_bounds[lower_active] - x[lower_active]
        normal[upper_active] = values.upper_bounds[upper_active] - x[upper_active]

        if self.nlp.equality_dimension:
            rhs = -values.equalities - values.equality_jacobian[:, ~linearization.free] @ normal[~linearization.free]
            y = linearization.factor.solve(rhs)
            normal[linearization.free] = linearization.free_jacobian.T @ y

        normal_norm = float(numpy.linalg.norm(normal))

        if normal_norm > trust_radius:
            normal *= trust_radius / normal_norm
            normal_norm = trust_radius

        tangential_radius = float(numpy.sqrt(max(0.0, trust_radius * trust_radius - normal_norm * normal_norm)))
        gradient_at_normal = values.gradient + values.hessian @ normal
        tangent = self._steihaug(gradient_at_normal, values.hessian, linearization, tangential_radius)
        compound = normal + tangent

        trial = self.program.evaluate(x + compound, parameters)
        correction = numpy.zeros_like(x)
        correction[lower_active] = values.lower_bounds[lower_active] - (x + compound)[lower_active]
        correction[upper_active] = values.upper_bounds[upper_active] - (x + compound)[upper_active]
        if self.nlp.equality_dimension:
            correction_rhs = -trial.equalities - values.equality_jacobian[:, ~linearization.free] @ correction[~linearization.free]
            correction[linearization.free] = linearization.free_jacobian.T @ linearization.factor.solve(correction_rhs)
        correction_norm = float(numpy.linalg.norm(correction))
        if correction_norm > trust_radius:
            correction *= trust_radius / correction_norm

        projected_gradient = -self._project(values.gradient, linearization)
        pg_norm = float(numpy.linalg.norm(projected_gradient))
        if pg_norm:
            projected_gradient *= trust_radius / pg_norm

        cauchy = self._cauchy_step(x, linearization, trust_radius)
        return _Step(
            compound,
            correction,
            projected_gradient,
            cauchy,
            normal_norm,
            float(numpy.linalg.norm(tangent)),
        )

    def _cauchy_step(
        self,
        x: numpy.ndarray,
        linearization: _Linearization,
        trust_radius: float,
    ) -> numpy.ndarray:
        values = linearization.values
        active_indices = numpy.flatnonzero(linearization.active)
        residual = numpy.concatenate(
            (
                values.equalities,
                numpy.where(
                    linearization.active[active_indices] < 0,
                    x[active_indices] - values.lower_bounds[active_indices],
                    x[active_indices] - values.upper_bounds[active_indices],
                ),
            )
        )
        if residual.size == 0:
            return numpy.zeros_like(x)
        jacobian = numpy.vstack(
            (
                values.equality_jacobian,
                numpy.eye(self.nlp.dimension)[active_indices],
            )
        )
        gradient = jacobian.T @ residual
        image = jacobian @ gradient
        denominator = float(image @ image)
        if denominator <= numpy.finfo(float).eps:
            return numpy.zeros_like(x)
        step = -(float(gradient @ gradient) / denominator) * gradient
        norm = float(numpy.linalg.norm(step))
        if norm > trust_radius:
            step *= trust_radius / norm
        return step

    def _steihaug(
        self,
        gradient: numpy.ndarray,
        hessian: numpy.ndarray,
        linearization: _Linearization,
        radius: float,
    ) -> numpy.ndarray:
        tangent = numpy.zeros(self.nlp.dimension)

        if radius <= numpy.finfo(float).eps:
            return tangent

        residual = -self._project(gradient, linearization)
        direction = residual.copy()
        residual_norm_sq = float(residual @ residual)

        if residual_norm_sq <= numpy.finfo(float).eps:
            return tangent

        hessian_norm = float(numpy.linalg.norm(hessian))

        for _ in range(self.options.cg_iterations):
            action = hessian @ direction + self.options.tangential_damping * hessian_norm * direction
            action = self._project(action, linearization)
            curvature = float(direction @ action)
            direction_norm_sq = float(direction @ direction)

            if curvature <= self.options.curvature_floor * direction_norm_sq:
                return tangent + _boundary_distance(tangent, direction, radius) * direction

            alpha = residual_norm_sq / curvature
            trial = tangent + alpha * direction

            if float(trial @ trial) >= radius * radius:
                return tangent + _boundary_distance(tangent, direction, radius) * direction

            tangent = trial
            new_residual = self._project(residual - alpha * action, linearization)
            new_norm_sq = float(new_residual @ new_residual)

            if new_norm_sq <= numpy.finfo(float).eps:
                return tangent

            direction = new_residual + (new_norm_sq / residual_norm_sq) * direction
            residual = new_residual
            residual_norm_sq = new_norm_sq

        return tangent

    def _multipliers(self, linearization: _Linearization) -> tuple[numpy.ndarray, numpy.ndarray]:
        values = linearization.values

        if self.nlp.equality_dimension:
            equality = linearization.factor.solve(-linearization.free_jacobian @ values.gradient[linearization.free])
        else:
            equality = numpy.empty(0)

        stationarity = values.gradient + values.equality_jacobian.T @ equality
        bounds = numpy.zeros(self.nlp.dimension)
        bounds[linearization.active < 0] = stationarity[linearization.active < 0]
        bounds[linearization.active > 0] = -stationarity[linearization.active > 0]

        return equality, bounds

    def _maintain_active_set(
        self,
        values: ModelValues,
        x: numpy.ndarray,
        bound_multipliers: numpy.ndarray,
        active: numpy.ndarray,
        fixed: numpy.ndarray,
        counters: numpy.ndarray,
        freeze: int,
    ) -> bool:
        tolerance = self.options.bound_tolerance
        removable = (active != 0) & ~fixed & (bound_multipliers < -tolerance)
        inactive = active == 0
        lower_violation = values.lower_bounds - x
        upper_violation = x - values.upper_bounds
        primal_violation = numpy.maximum(lower_violation, upper_violation)

        for i in range(self.nlp.dimension):
            offending = removable[i] if active[i] else primal_violation[i] > tolerance
            counters[i] = counters[i] + 1 if offending else 0

        if freeze > 0:
            return False

        delayed = counters >= self.options.activation_delay
        removal_indices = numpy.flatnonzero(removable & delayed)

        if removal_indices.size:
            index = int(removal_indices[numpy.argmin(bound_multipliers[removal_indices])])
            active[index] = 0
            counters[index] = 0

            return True

        activation_indices = numpy.flatnonzero(inactive & delayed & (primal_violation > tolerance))

        if activation_indices.size:
            index = int(activation_indices[numpy.argmax(primal_violation[activation_indices])])
            active[index] = -1 if lower_violation[index] >= upper_violation[index] else 1
            counters[index] = 0

            if self.nlp.equality_dimension + numpy.count_nonzero(active) > self.nlp.dimension:
                raise ActiveSetError("activating a bound overdetermined the working set")

            return True

        return False


def _boundary_distance(point: numpy.ndarray, direction: numpy.ndarray, radius: float) -> float:
    a = float(direction @ direction)

    if a == 0.0:
        return 0.0

    b = float(point @ direction)
    discriminant = max(0.0, b * b + a * (radius * radius - float(point @ point)))

    return max(0.0, (-b + numpy.sqrt(discriminant)) / a)


def _violation(values: ModelValues, x: numpy.ndarray) -> float:
    equality = float(numpy.max(numpy.abs(values.equalities))) if values.equalities.size else 0.0
    lower = float(numpy.max(numpy.maximum(values.lower_bounds - x, 0.0)))
    upper = float(numpy.max(numpy.maximum(x - values.upper_bounds, 0.0)))
    return max(equality, lower, upper)


def create_solver(nlp: NonlinearProgram, options: SolverOptions | None = None) -> Solver:
    """Symbolically derive and create a callable, problem-specific SQP solver."""
    return Solver(GeneratedProgram(nlp), options or SolverOptions())
