"""Numerical Byrd--Omojokun SQP solver."""

from collections.abc import Sequence
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Literal, cast, overload

import numpy

from .model import NonlinearProgram
from .options import SolverOptions
from .program import EvaluatorIR, GeneratedProgram, LDLFactor, ModelValues


class Procedure(StrEnum):
    """Identify the procedure performed during an SQP iteration."""

    ACTIVE_SET_UPDATE = "active-set-update"
    BYRD_OMOJOKUN_SOC = "byrd-omojukun-soc"
    BYRD_OMOJOKUN = "byrd-omojukun"
    PROJECTED_GRADIENT = "projected-gradient"
    CAUCHY = "cauchy"
    REJECTED = "rejected"


class ActiveSetError(RuntimeError):
    """Indicate that the bound working set is structurally invalid."""


@dataclass(slots=True)
class IterationDiagnostics:
    """Record the outcome of one SQP iteration.

    Attributes
    ----------
    procedure
        Step procedure selected by the filter.
    accepted
        Whether any trial point was accepted.
    x
        Accepted iterate, or the unchanged current iterate after rejection.
    objective
        Objective value at ``x``.
    violation
        Infinity norm of the equality residuals at ``x``. Box feasibility is
        maintained directly and is not part of the filter.
    trust_radius
        Trust-region radius prepared for the following iteration.
    normal_step_norm
        Euclidean norm of the normal step.
    tangential_step_norm
        Euclidean norm of the tangential step.
    correction_step_norm
        Euclidean norm of the second-order correction.
    active_bounds
        Bound working set, using ``-1`` for lower, ``0`` for inactive, and
        ``1`` for upper bounds.
    equality_multipliers
        Estimated equality multipliers.
    bound_multipliers
        Estimated active-bound multipliers.
    """

    procedure: Procedure
    accepted: bool
    x: numpy.ndarray
    objective: float
    violation: float
    trust_radius: float
    normal_step_norm: float
    tangential_step_norm: float
    correction_step_norm: float
    active_bounds: numpy.ndarray
    equality_multipliers: numpy.ndarray
    bound_multipliers: numpy.ndarray


@dataclass(slots=True)
class SolverDiagnostics:
    """Collect diagnostics produced by a complete solver invocation.

    Attributes
    ----------
    iterations
        Diagnostics in SQP iteration order.
    """

    iterations: list[IterationDiagnostics] = field(default_factory=list)


@dataclass(slots=True)
class SolverResult:
    """Store a solution together with its iteration diagnostics.

    Attributes
    ----------
    x
        Final decision-variable vector.
    diagnostics
        Diagnostics collected during the fixed SQP iteration sequence.
    """

    x: numpy.ndarray
    diagnostics: SolverDiagnostics


@dataclass(slots=True)
class _Linearization:
    """Bundle a model linearization and its reusable equality factorization.

    Attributes
    ----------
    values
        Objective, derivative, constraint, and bound values at the iterate.
    active
        Bound working set at the iterate.
    free
        Boolean mask selecting variables without active bounds.
    free_jacobian
        Equality Jacobian restricted to free variables.
    factor
        LDL factorization of the regularized free-variable equality Gramian.
    """

    values: ModelValues
    active: numpy.ndarray
    free: numpy.ndarray
    free_jacobian: numpy.ndarray
    factor: LDLFactor


@dataclass(slots=True)
class _Step:
    """Bundle the primary Byrd--Omojokun step and its fallback steps.

    Attributes
    ----------
    compound
        Sum of the normal and tangential steps.
    correction
        Second-order correction to the compound step.
    projected_gradient
        Projected-gradient fallback step.
    cauchy
        Constraint-model Cauchy fallback step.
    normal_norm
        Euclidean norm of the normal step.
    tangential_norm
        Euclidean norm of the tangential step.
    """

    compound: numpy.ndarray
    correction: numpy.ndarray
    projected_gradient: numpy.ndarray
    cauchy: numpy.ndarray
    normal_norm: float
    tangential_norm: float


class _Filter:
    def __init__(self, beta: float, gamma: float) -> None:
        self.beta = beta
        self.gamma = gamma
        self.entries: list[tuple[float, float]] = []

    def add_initial(self, objective: float, violation: float) -> None:
        self.entries.append((objective, violation))

    def accepts(self, objective: float, violation: float) -> bool:
        accepted = all(objective + self.gamma * violation <= old_objective or violation <= (1.0 - self.beta) * old_violation for old_objective, old_violation in self.entries)
        if accepted:
            self.entries.append((objective, violation))
        return accepted


class Solver:
    """Callable generated Byrd--Omojokun optimizer."""

    def __init__(self, program: GeneratedProgram, options: SolverOptions) -> None:
        self.program = program
        self.options = options

    @property
    def nlp(self) -> NonlinearProgram:
        """Return the nonlinear program represented by this solver."""
        return self.program.nlp

    @property
    def ast(self) -> EvaluatorIR:
        """The SymPy evaluator IR used by this generated solver."""
        return self.program.ir

    @overload
    def __call__(
        self,
        initial_guess: Sequence[float] | numpy.ndarray,
        parameters: Sequence[float] | numpy.ndarray = (),
        *,
        diagnostics: Literal[False] = False,
    ) -> numpy.ndarray: ...

    @overload
    def __call__(
        self,
        initial_guess: Sequence[float] | numpy.ndarray,
        parameters: Sequence[float] | numpy.ndarray = (),
        *,
        diagnostics: Literal[True],
    ) -> SolverResult: ...

    def __call__(
        self,
        initial_guess: Sequence[float] | numpy.ndarray,
        parameters: Sequence[float] | numpy.ndarray = (),
        *,
        diagnostics: bool = False,
    ) -> numpy.ndarray | SolverResult:
        """Solve the NLP and optionally return iteration diagnostics."""
        result = self.solve(initial_guess, parameters)
        return result if diagnostics else result.x

    def solve(  # noqa: PLR0915
        self,
        initial_guess: Sequence[float] | numpy.ndarray,
        parameters: Sequence[float] | numpy.ndarray = (),
    ) -> SolverResult:
        """Execute the fixed number of generated SQP iterations."""
        x = numpy.asarray(initial_guess, dtype=float).reshape(-1).copy()
        params = numpy.asarray(parameters, dtype=float).reshape(-1)

        if x.size != self.nlp.dimension:
            message = f"expected {self.nlp.dimension} initial values, got {x.size}"
            raise ValueError(message)

        if params.size != len(self.nlp.parameters):
            message = f"expected {len(self.nlp.parameters)} parameters, got {params.size}"
            raise ValueError(message)

        if not numpy.all(numpy.isfinite(x)) or not numpy.all(numpy.isfinite(params)):
            message = "initial values and parameters must be finite"
            raise ValueError(message)

        initial = self.program.evaluate(x, params)
        x = numpy.minimum(numpy.maximum(x, initial.lower_bounds), initial.upper_bounds)
        initial = self.program.evaluate(x, params)
        active = numpy.zeros(self.nlp.dimension, dtype=numpy.int8)
        fixed = (
            numpy.isfinite(initial.lower_bounds) & numpy.isfinite(initial.upper_bounds) & (numpy.abs(initial.upper_bounds - initial.lower_bounds) <= self.options.bound_tolerance)
        )
        active[fixed] = -1
        trust_radius = self.options.initial_trust_radius
        candidate_filter = _Filter(self.options.filter_beta, self.options.filter_gamma)
        candidate_filter.add_initial(initial.objective, _equality_violation(initial))
        diagnostics = SolverDiagnostics()

        for _ in range(self.options.sqp_iterations):
            current = self.program.evaluate(x, params)
            linearization = self._linearize(current, active)
            equality_multipliers, bound_multipliers = self._multipliers(linearization)
            removable = self._removable_bound(current, x, active, fixed, bound_multipliers)

            if removable is not None:
                active[removable] = 0
                diagnostics.iterations.append(
                    IterationDiagnostics(
                        Procedure.ACTIVE_SET_UPDATE,
                        False,
                        x.copy(),
                        current.objective,
                        _equality_violation(current),
                        trust_radius,
                        0.0,
                        0.0,
                        0.0,
                        active.copy(),
                        equality_multipliers.copy(),
                        bound_multipliers.copy(),
                    )
                )
                continue

            step = self._step(x, params, linearization, trust_radius)
            blocking = self._blocking_bounds(x, step.compound, current, active)

            if blocking.size:
                for index in blocking:
                    active[index] = -1 if step.compound[index] < 0.0 else 1
                if self.nlp.equality_dimension + numpy.count_nonzero(active) > self.nlp.dimension:
                    message = "blocking bounds overdetermined the working set"
                    raise ActiveSetError(message)
                diagnostics.iterations.append(
                    IterationDiagnostics(
                        Procedure.ACTIVE_SET_UPDATE,
                        False,
                        x.copy(),
                        current.objective,
                        _equality_violation(current),
                        trust_radius,
                        step.normal_norm,
                        step.tangential_norm,
                        float(numpy.linalg.norm(step.correction)),
                        active.copy(),
                        equality_multipliers.copy(),
                        bound_multipliers.copy(),
                    )
                )
                continue

            attempts = []
            corrected = step.compound + step.correction
            if self._box_feasible(x + corrected, current):
                attempts.append((Procedure.BYRD_OMOJOKUN_SOC, corrected))
            attempts.append((Procedure.BYRD_OMOJOKUN, step.compound))
            if self._box_feasible(x + step.projected_gradient, current):
                attempts.append((Procedure.PROJECTED_GRADIENT, step.projected_gradient))
            if self._box_feasible(x + step.cauchy, current):
                attempts.append((Procedure.CAUCHY, step.cauchy))
            accepted = False
            chosen_procedure = Procedure.REJECTED
            chosen_step = numpy.zeros_like(x)
            chosen_values = current
            chosen_x = x
            for procedure, trial_step in attempts:
                trial_x = x + trial_step
                trial = self.program.evaluate(trial_x, params)
                trial_violation = _equality_violation(trial)
                if candidate_filter.accepts(trial.objective, trial_violation):
                    accepted = True
                    chosen_procedure = procedure
                    chosen_step = trial_step
                    chosen_values = trial
                    chosen_x = trial_x
                    break

            if accepted:
                x = chosen_x.copy()
                actual_norm = float(numpy.linalg.norm(chosen_step))
                trust_radius = self.options.trust_expand * actual_norm
            else:
                trust_radius *= self.options.trust_shrink
                scheduled = (active != 0) & ~fixed & ~self._geometrically_active(current, x, active)
                active[scheduled] = 0

            trust_radius = max(trust_radius, numpy.finfo(float).eps)
            diagnostics.iterations.append(
                IterationDiagnostics(
                    chosen_procedure,
                    accepted,
                    x.copy(),
                    chosen_values.objective if accepted else current.objective,
                    _equality_violation(chosen_values) if accepted else _equality_violation(current),
                    trust_radius,
                    step.normal_norm,
                    step.tangential_norm,
                    float(numpy.linalg.norm(step.correction)),
                    active.copy(),
                    equality_multipliers.copy(),
                    bound_multipliers.copy(),
                )
            )

        return SolverResult(x, diagnostics)

    def _linearize(self, values: ModelValues, active: numpy.ndarray) -> _Linearization:
        number_active = int(numpy.count_nonzero(active))
        if self.nlp.equality_dimension + number_active > self.nlp.dimension:
            message = "equalities plus active bounds exceed the number of variables"
            raise ActiveSetError(message)
        free = active == 0
        free_jacobian = values.equality_jacobian[:, free]
        gram = self.program.assemble_equality_gram(
            values.equality_jacobian,
            free,
            self.options.equality_regularization,
        )
        factor = self.program.ldl.factor(gram, self.options.factorization_tolerance)
        return _Linearization(values, active.copy(), free, free_jacobian, factor)

    def _project(self, vector: numpy.ndarray, linearization: _Linearization) -> numpy.ndarray:
        projected = numpy.zeros_like(vector)
        free_values = vector[linearization.free]
        if self.nlp.equality_dimension:
            correction = linearization.factor.solve(linearization.free_jacobian @ free_values)
            free_values = free_values - linearization.free_jacobian.T @ correction
        projected[linearization.free] = free_values
        return projected

    def _step(self, x: numpy.ndarray, parameters: numpy.ndarray, linearization: _Linearization, trust_radius: float) -> _Step:
        values = linearization.values
        normal = numpy.zeros_like(x)
        lower_active = linearization.active < 0
        upper_active = linearization.active > 0
        normal[lower_active] = values.lower_bounds[lower_active] - x[lower_active]
        normal[upper_active] = values.upper_bounds[upper_active] - x[upper_active]

        if self.nlp.equality_dimension:
            rhs = -values.equalities - values.equality_jacobian[:, ~linearization.free] @ normal[~linearization.free]
            y = linearization.factor.solve(rhs)
            normal[linearization.free] = linearization.free_jacobian.T @ y

        normal_norm = float(numpy.linalg.norm(normal))

        if normal_norm > trust_radius:
            normal *= trust_radius / normal_norm
            normal_norm = trust_radius

        tangential_radius = float(numpy.sqrt(max(0.0, trust_radius * trust_radius - normal_norm * normal_norm)))
        gradient_at_normal = values.gradient + values.hessian @ normal
        tangent = self._steihaug(gradient_at_normal, values.hessian, linearization, tangential_radius)
        compound = normal + tangent

        trial = self.program.evaluate(x + compound, parameters)
        correction = numpy.zeros_like(x)
        correction[lower_active] = values.lower_bounds[lower_active] - (x + compound)[lower_active]
        correction[upper_active] = values.upper_bounds[upper_active] - (x + compound)[upper_active]
        if self.nlp.equality_dimension:
            correction_rhs = -trial.equalities - values.equality_jacobian[:, ~linearization.free] @ correction[~linearization.free]
            correction[linearization.free] = linearization.free_jacobian.T @ linearization.factor.solve(correction_rhs)
        correction_norm = float(numpy.linalg.norm(correction))
        if correction_norm > trust_radius:
            correction *= trust_radius / correction_norm

        projected_gradient = -self._project(values.gradient, linearization)
        pg_norm = float(numpy.linalg.norm(projected_gradient))
        if pg_norm:
            projected_gradient *= trust_radius / pg_norm

        cauchy = self._cauchy_step(x, linearization, trust_radius)
        return _Step(
            compound,
            correction,
            projected_gradient,
            cauchy,
            normal_norm,
            float(numpy.linalg.norm(tangent)),
        )

    def _cauchy_step(self, x: numpy.ndarray, linearization: _Linearization, trust_radius: float) -> numpy.ndarray:
        values = linearization.values
        active_indices = numpy.flatnonzero(linearization.active)
        residual = numpy.concatenate(
            (
                values.equalities,
                numpy.where(
                    linearization.active[active_indices] < 0,
                    x[active_indices] - values.lower_bounds[active_indices],
                    x[active_indices] - values.upper_bounds[active_indices],
                ),
            )
        )
        if residual.size == 0:
            return numpy.zeros_like(x)
        jacobian = numpy.vstack(
            (
                values.equality_jacobian,
                numpy.eye(self.nlp.dimension)[active_indices],
            )
        )
        gradient = jacobian.T @ residual
        image = jacobian @ gradient
        denominator = float(image @ image)
        if denominator <= numpy.finfo(float).eps:
            return numpy.zeros_like(x)
        step = -(float(gradient @ gradient) / denominator) * gradient
        norm = float(numpy.linalg.norm(step))
        if norm > trust_radius:
            step *= trust_radius / norm
        return cast(numpy.ndarray, step)

    def _steihaug(self, gradient: numpy.ndarray, hessian: numpy.ndarray, linearization: _Linearization, radius: float) -> numpy.ndarray:
        tangent = numpy.zeros(self.nlp.dimension)

        if radius <= numpy.finfo(float).eps:
            return tangent

        residual = -self._project(gradient, linearization)
        direction = residual.copy()
        residual_norm_sq = float(residual @ residual)

        if residual_norm_sq <= numpy.finfo(float).eps:
            return tangent

        hessian_norm = float(numpy.linalg.norm(hessian))

        for _ in range(self.options.cg_iterations):
            action = hessian @ direction + self.options.tangential_damping * hessian_norm * direction
            action = self._project(action, linearization)
            curvature = float(direction @ action)
            direction_norm_sq = float(direction @ direction)

            if curvature <= self.options.curvature_floor * direction_norm_sq:
                return tangent + _boundary_distance(tangent, direction, radius) * direction

            alpha = residual_norm_sq / curvature
            trial = tangent + alpha * direction

            if float(trial @ trial) >= radius * radius:
                return tangent + _boundary_distance(tangent, direction, radius) * direction

            tangent = trial
            new_residual = self._project(residual - alpha * action, linearization)
            new_norm_sq = float(new_residual @ new_residual)

            if new_norm_sq <= numpy.finfo(float).eps:
                return tangent

            direction = new_residual + (new_norm_sq / residual_norm_sq) * direction
            residual = new_residual
            residual_norm_sq = new_norm_sq

        return tangent

    def _multipliers(self, linearization: _Linearization) -> tuple[numpy.ndarray, numpy.ndarray]:
        values = linearization.values

        if self.nlp.equality_dimension:
            equality = linearization.factor.solve(-linearization.free_jacobian @ values.gradient[linearization.free])
        else:
            equality = numpy.empty(0)

        stationarity = values.gradient + values.equality_jacobian.T @ equality
        bounds = numpy.zeros(self.nlp.dimension)
        bounds[linearization.active < 0] = stationarity[linearization.active < 0]
        bounds[linearization.active > 0] = -stationarity[linearization.active > 0]

        return equality, bounds

    def _geometrically_active(self, values: ModelValues, x: numpy.ndarray, active: numpy.ndarray) -> numpy.ndarray:
        tolerance = self.options.bound_tolerance
        lower = (active < 0) & (numpy.abs(x - values.lower_bounds) <= tolerance)
        upper = (active > 0) & (numpy.abs(x - values.upper_bounds) <= tolerance)
        return cast(numpy.ndarray, lower | upper)

    def _removable_bound(self, values: ModelValues, x: numpy.ndarray, active: numpy.ndarray, fixed: numpy.ndarray, multipliers: numpy.ndarray) -> int | None:
        removable = self._geometrically_active(values, x, active) & ~fixed & (multipliers < -self.options.bound_tolerance)
        indices = numpy.flatnonzero(removable)
        if not indices.size:
            return None
        return int(indices[numpy.argmin(multipliers[indices])])

    def _blocking_bounds(self, x: numpy.ndarray, step: numpy.ndarray, values: ModelValues, active: numpy.ndarray) -> numpy.ndarray:
        tolerance = self.options.bound_tolerance
        fractions = numpy.full(self.nlp.dimension, numpy.inf)
        free = active == 0
        toward_upper = free & (step > tolerance) & numpy.isfinite(values.upper_bounds)
        toward_lower = free & (step < -tolerance) & numpy.isfinite(values.lower_bounds)
        fractions[toward_upper] = (values.upper_bounds[toward_upper] - x[toward_upper]) / step[toward_upper]
        fractions[toward_lower] = (values.lower_bounds[toward_lower] - x[toward_lower]) / step[toward_lower]
        first = float(numpy.min(fractions))
        if not numpy.isfinite(first) or first > 1.0 + tolerance:
            return numpy.empty(0, dtype=int)
        tie_tolerance = tolerance * max(1.0, abs(first))
        return numpy.flatnonzero(numpy.abs(fractions - first) <= tie_tolerance)

    def _box_feasible(self, x: numpy.ndarray, values: ModelValues) -> bool:
        tolerance = self.options.bound_tolerance
        return bool(numpy.all(x >= values.lower_bounds - tolerance) and numpy.all(x <= values.upper_bounds + tolerance))


def _boundary_distance(point: numpy.ndarray, direction: numpy.ndarray, radius: float) -> float:
    a = float(direction @ direction)

    if a == 0.0:
        return 0.0

    b = float(point @ direction)
    discriminant = max(0.0, b * b + a * (radius * radius - float(point @ point)))

    return float(max(0.0, (-b + numpy.sqrt(discriminant)) / a))


def _equality_violation(values: ModelValues) -> float:
    return float(numpy.max(numpy.abs(values.equalities))) if values.equalities.size else 0.0


def create_solver(nlp: NonlinearProgram, options: SolverOptions | None = None) -> Solver:
    """Symbolically derive and create a callable, problem-specific SQP solver."""
    return Solver(GeneratedProgram(nlp), options or SolverOptions())
